export const CLIENTS = [
    "SPORTFIVE", "JUVENTUS", "THE RING", "eLIGUE 1", "BR FOOTBALL",
    "FFBB", "ATHLE", "SANOFI", "eCDF", "PANINI", "FFF × INTERMARCHÉ",
    "FIFA e", "ETF26", "TEAM MALIZIA", "SURAVENIR", "ANDROS SPORT",
    "ARKEMA SPORT", "PRIME NBA", "STADE FRANÇAIS", "PSG", "OM",
    "LNH", "OC SPORT"
];
